package com.foo.cayenne.auto;

import java.time.LocalDateTime;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.foo.cayenne.Team;

/**
 * Class _Game was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Game extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ARENA = Property.create("arena", String.class);
    public static final Property<LocalDateTime> DATE_TIME = Property.create("dateTime", LocalDateTime.class);
    public static final Property<Team> HOME_TEAM = Property.create("homeTeam", Team.class);
    public static final Property<Team> VISITING_TEAM = Property.create("visitingTeam", Team.class);

    public void setArena(String arena) {
        writeProperty("arena", arena);
    }
    public String getArena() {
        return (String)readProperty("arena");
    }

    public void setDateTime(LocalDateTime dateTime) {
        writeProperty("dateTime", dateTime);
    }
    public LocalDateTime getDateTime() {
        return (LocalDateTime)readProperty("dateTime");
    }

    public void setHomeTeam(Team homeTeam) {
        setToOneTarget("homeTeam", homeTeam, true);
    }

    public Team getHomeTeam() {
        return (Team)readProperty("homeTeam");
    }


    public void setVisitingTeam(Team visitingTeam) {
        setToOneTarget("visitingTeam", visitingTeam, true);
    }

    public Team getVisitingTeam() {
        return (Team)readProperty("visitingTeam");
    }


}
