package com.foo.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.foo.cayenne.Game;

/**
 * Class _Team was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Team extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<Game>> GAMES = Property.create("games", List.class);
    public static final Property<List<Game>> GAMES1 = Property.create("games1", List.class);

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToGames(Game obj) {
        addToManyTarget("games", obj, true);
    }
    public void removeFromGames(Game obj) {
        removeToManyTarget("games", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Game> getGames() {
        return (List<Game>)readProperty("games");
    }


    public void addToGames1(Game obj) {
        addToManyTarget("games1", obj, true);
    }
    public void removeFromGames1(Game obj) {
        removeToManyTarget("games1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Game> getGames1() {
        return (List<Game>)readProperty("games1");
    }


}
